# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80418e6a1723d7ab8c601fa8a6ecf4a047bb91c2868c687c613cbafa4f202b7b793349b2c6b2716878a138a453fe621bd39676678dc8b5e8a9b3570540b48a4f

test:
  secret_key_base: 6d0a993a01153567e6a8989350a73ab9113fc904d9e195b7f60cc2aa1c72c1f156f926286c76a2cfbd5aaa5208e378547777c037d6f068a665292f695926bf73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
